### Common

info:
  build:
    artifact: @project.artifactId@
    name: @project.name@
    description: @project.description@
    version: @project.version@

server:
  port: 33002
  tomcat:
    max-threads: 4

spring:
  application:
    name: UAA
  profiles:
    active: dev
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  liquibase:
    change-log: "classpath:/db/changelog/db.changelog-master.yml"
    enabled: true

logging:
  level:
    root: INFO

com:
  chumbok:
    security:
      enable: true
      assert-org-with: Chumbok
      assert-tenant: true
      assert-tenant-with: Chumbok
    uaa:
      jwt:
        token-expiration-time-in-second: 3600
        refresh-token-expiration-time-in-second: 1800
        token-issuer: Chumbok

---

### Dev profile

spring:
  profiles: dev
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: ${DB_URL:jdbc:h2:mem:uaa;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL}
    username: sa
    password:
    driver-class: org.h2.Driver
    jpa:
      show-sql: true

eureka:
  client:
    enabled: false

logging:
  level:
    com.chumbok: DEBUG
    org.springframework.security: DEBUG

com:
  chumbok:
    uaa:
      jwt:
        token-signing-private-key-path: "classpath:dev-keys/private_key.der"
    auth:
      token-signing-public-key-path: "classpath:dev-keys/public_key.der"

---

### Prod profile

spring:
  profiles: prod
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/uaa?serverTimezone=UTC}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: validate

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:33000/eureka/

logging:
  level:
    com.chumbok: DEBUG

---


### MySQL profile

spring:
  profiles: mysql
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/uaa?createDatabaseIfNotExist=true&serverTimezone=UTC}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}


---

### Integration test profile

spring:
  profiles: it
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: ${DB_URL:jdbc:h2:mem:uaa;DB_CLOSE_ON_EXIT=TRUE;MODE=MYSQL}
    username: sa
    password:
    driver-class: org.h2.Driver
    jpa:
      show-sql: true
  main:
    allow-bean-definition-overriding: true

com:
  chumbok:
    uaa:
      jwt:
        token-signing-private-key-path: "classpath:dev-keys/private_key.der"
    auth:
      token-signing-public-key-path: "classpath:dev-keys/public_key.der"

---

### Debug profile

spring:
  profiles: debug

logging:
  level:
    org.hibernate:
      SQL: DEBUG
      type.descriptor.sql.BasicBinder: TRACE


---

spring:
  profiles: docker

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:33000/eureka/

com:
  chumbok:
    uaa:
      jwt:
        token-signing-private-key-path: /root/keys/private_key.der
    auth:
      token-signing-public-key-path: /root/keys/public_key.der

---

### Enable Eureka profile

spring:
  profiles: eureka

eureka:
  client:
    enabled: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:33000/eureka/
