apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdA== #root
  MYSQL_DATABASE: Y2h1bWJvay1kYg== #chumbok-db
  MYSQL_USER: YXBw #app
  MYSQL_PASSWORD: YXBw #app