apiVersion: v1
kind: PersistentVolume
metadata:
  name: chumbok-security-key-persistent-storage
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: /Users/mossaddeque/Desktop/key